spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    livereload:
      enabled: true
  output:
    ansi:
      enabled: DETECT
  datasource:
    url: jdbc:mariadb://43.200.83.147:13306/onepiece
    username: root
    password: 81fa30619
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: itk-scheduled-task-pool

custom:
  path:
    files: /home/jar_home/onepiece/files/
server:
  port: 80
logging:
  file:
    name: app
    path: /home/jar_home/onepiece/app
mybatis:
  type-aliases-package: onepiece.bounty.rush.domain
  mapper-locations: classpath:mapper/**/*.xml

myapp:
  loginFailCnt: 10

---
spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: DETECT
  datasource:
    url: jdbc:mariadb://43.200.83.147:13306/onepiece
    username: root
    password: 81fa30619
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: itk-scheduled-task-pool
custom:
  path:
    files: 'c:/one/'

server:
  #  port: 20093  # 개발서버
  port: 15271  # 옥천서버
logging:
  file:
    name: app
    path: 'c:/one/files'

mybatis:
  type-aliases-package: onepiece.bounty.rush.domain
  mapper-locations: classpath:mapper/**/*.xml

myapp:
  loginFailCnt: 10